### ISSUE TITLE
headerの作成

### ISSUE THREAD

**Issue by yabukichi** [yabukichi/lagoon-website#2]
レスポンシブはいったん無しで、headerを作成する。

bootstrapのnavを使ってください。

https://getbootstrap.com/docs/4.3/components/navbar/

<img width="628" alt="スクリーンショット 2020-01-29 15 22 25" src="https://user-images.githubusercontent.com/37928681/73339675-9c318f80-42bc-11ea-8419-74496609916e.png">

**Comment by mako4kamiya** [comment]
**作業の進め方**
- index.htmlのheaderの`<!-- タスク２ -->`部分にhtmlを入力

- _header.scssの`// タスク２`部分にcssを書く。

**Comment by mako4kamiya** [comment]
作業開始！

**Comment by mako4kamiya** [comment]
HTML終了。CSSは明日。

**Comment by mako4kamiya** [comment]
作業開始！

**Comment by yabukichi** [comment]
レスポンシブ込で4000円でお願いします！
