### ISSUE TITLE
home/servicesの作成

### ISSUE THREAD

**Issue by yabukichi** [yabukichi/lagoon-website#4]
ホームページのservice部分を作成する。

<img width="729" alt="services" src="https://user-images.githubusercontent.com/37928681/73345079-c12b0000-42c6-11ea-8a82-bd9eaa32b66a.png">

**Comment by mako4kamiya** [comment]
index.htmlの`<!-- タスク4 -->`部分にhtmlを入力

homeフォルダの_services.scssの`// タスク4`の部分にcssを書く

**Comment by dakuto** [comment]
お疲れさまです。
makoちゃんの指示を踏まえて、servisesのコーディングします。

**Comment by yabukichi** [comment]
6000円でお願いします！
