### ISSUE TITLE
【ホームページ】home/workspaceの作成

### ISSUE THREAD

**Issue by yabukichi** [yabukichi/lagoon-website#5]
ホームページのworkspace部分を作成する。

#3 と類似。

<img width="726" alt="workspace" src="https://user-images.githubusercontent.com/37928681/73345153-e6b80980-42c6-11ea-9c56-e03ea1efb431.png">

**Comment by mako4kamiya** [comment]
index.htmlの`<!-- タスク5 -->`部分にhtmlを入力

homeフォルダの_workspace.scssの`// タスク5`の部分にcssを書く

**Comment by yabukichi** [comment]
レスポンシブ込で6000円でお願いします！
